### ISSUE TITLE
Yaml file needs ports declaration

### ISSUE THREAD

**Issue by mprofitlich** [ddev/ddev-browsersync#33]

**Comment by rfay** [comment]
It would be kind to explain more in your issue, but no, the docker-compose.browsersync.yaml does not need or want a `ports` stanza. If it had one, you could only run one project on a system. Instead, it has an `expose` (which exposes inside docker's world) and HTTP_EXPOSE/HTTPS_EXPOSE, which expose it via ddev-router (which handles it per-hostname)

https://github.com/drud/ddev-browsersync/blob/1743545298d5c48397eb9d88e801e053f2df7a24/docker-compose.browsersync.yaml#L6-L10

**Comment by manuelmeister** [comment]
How could I set a different port? (instead of 3000)

**Comment by manuelmeister** [comment]
Currently this is not fully changeable: https://github.com/drud/ddev-browsersync/blob/main/commands/web/browsersync#L9

**Comment by tyler36** [comment]
The follow steps show how to replace the port from `3000` to `8080`

In `.ddev/browser-sync.js`:
   - Remove `// #ddev-generated`
   - Set the port number.

   ```js
   module.exports = {
       port: 8080,
   ```

In `.ddev/docker-compose.browsersync.yaml`
   - Remove `// #ddev-generated`
   - replace 4 instances of the port
   
    ```yml
    expose:
      - '8080'
    environment:
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,3001:8080
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,8080:8080
    ```

In `~/.ddev/commands/web/browsersync`:
   - Remove `// #ddev-generated`
   - replace 1 instances of the port

   ```js
   echo "Proxying browsersync on ${DDEV_PRIMARY_URL}:8080"
   ```
