### ISSUE TITLE
Connection refused on port 3000 (DDEV + WP + ViteJS)

### ISSUE THREAD

**Issue by jmaleman** [ddev/ddev-browsersync#49]
I'm working on a project with DDEV + WP + ViteJS on a Linux (Ubuntu). It's running correctly and I want to add ddev-browsersync to the project, but I not be able to reach `:3000` port with DDEV url.

**config.yaml**
```yaml
...
web_extra_exposed_ports:
    - name: ViteJS
      container_port: 5173
      http_port: 5172
      https_port: 5173
...
``` 
And an extra configuration file **docker-compose.vite_extra.yaml** for this:
```yaml
services:
  web:
    expose:
      - "5173"
    environment:
      HTTP_EXPOSE: ${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,5174:5173
      HTTPS_EXPOSE: ${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,5173:5173
```

When VIteJS configuration files are enable I can reach port `:3000` and browser indcates "ERR_CONNECTION_REFUSED".

¿Should be add an extra_exposed_ports on DDEV configuration file to achieve `:3000` like I did with ViteJS?

Thanks!
